[workspace]
release = false
publish = false
changelog_config = "cliff.toml"

[[package]]
name = "timeseries-table-format"
release = true
changelog_path = "CHANGELOG.md"
changelog_include = ["timeseries-table-cli", "timeseries-table-python"]
git_tag_name = "timeseries-table-format-v{{ version }}"

[[package]]
name = "timeseries-table-cli"
release = true
git_only = true
git_tag_name = "timeseries-table-format-v{{ version }}"
git_tag_enable = false
git_release_enable = false
changelog_update = false

[[package]]
name = "timeseries-table-python"
release = true
publish = false
git_only = true
git_tag_name = "timeseries-table-format-v{{ version }}"
git_tag_enable = false
git_release_enable = false
changelog_update = false
semver_check = false
