[package]
name = "timeseries-table-python"
version = "0.1.5"
edition = "2024"
rust-version.workspace = true
publish = false


[dependencies]
arrow-array = { workspace = true, features = ["ffi"]}
arrow-ipc = { workspace = true }
datafusion = { workspace = true }

pyo3 = { version = "0.28", features = ["abi3-py310"] }

futures-util = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }

timeseries-table-format = { path = "../timeseries-table-format", version = "0.1.5", default-features = false, features = ["datafusion"] }


[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
name = "_native"

[features]
default = []
test-utils = []
ipc-zstd = ["arrow-ipc/zstd"]
