[package]
name = "timeseries-table-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false


[dependencies]
arrow-array = { workspace = true, features = ["ffi"]}
arrow-ipc = { workspace = true }
datafusion = { workspace = true }

pyo3 = { version = "0.29", features = ["abi3-py310"] }

futures-util = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }

timeseries-table-format = { workspace = true, features = ["datafusion"] }


[lints]
workspace = true

[lib]
crate-type = ["cdylib"]
name = "_native"

[features]
default = []
test-utils = []
ipc-zstd = ["arrow-ipc/zstd"]
