#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import pathlib
import subprocess
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
STAMP_PATH = REPO_ROOT / "crates" / "timeseries-table-python" / "python-src.stamp"

WHEEL_INPUT_PREFIXES: tuple[str, ...] = (
    "python/pyproject.toml",
    "python/README.md",
    "python/src",
)


def _git_worktree_file_blobs(
    repo_root: pathlib.Path = REPO_ROOT,
    prefixes: tuple[str, ...] = WHEEL_INPUT_PREFIXES,
) -> list[tuple[str, str]]:
    # Hash normalized Git blobs from the working tree so unstaged changes are included without
    # making the result depend on core.autocrlf.
    try:
        out = subprocess.check_output(
            [
                "git",
                "-C",
                str(repo_root),
                "ls-files",
                "--cached",
                "--others",
                "--exclude-standard",
                "-z",
                "--",
                *prefixes,
            ],
            stderr=subprocess.DEVNULL,
        )
        paths = sorted({raw.decode("utf-8") for raw in out.split(b"\0") if raw})
        pairs = []
        for path in paths:
            if not (repo_root / path).is_file():
                continue
            oid = subprocess.check_output(
                [
                    "git",
                    "-C",
                    str(repo_root),
                    "hash-object",
                    f"--path={path}",
                    "--",
                    path,
                ],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
            pairs.append((path, oid))
        return pairs
    except (OSError, subprocess.CalledProcessError, UnicodeError):
        return []


def _hash_inputs(
    repo_root: pathlib.Path = REPO_ROOT,
    prefixes: tuple[str, ...] = WHEEL_INPUT_PREFIXES,
) -> tuple[str, int]:
    h = hashlib.sha256()
    blobs = _git_worktree_file_blobs(repo_root, prefixes)
    if not blobs:
        raise RuntimeError("Could not find wheel inputs; run from a git checkout.")

    for path, oid in blobs:
        h.update(path.encode("utf-8"))
        h.update(b"\0")
        h.update(oid.encode("ascii"))
        h.update(b"\0")

    return h.hexdigest(), len(blobs)


def _read_stamp_sha256() -> str | None:
    if not STAMP_PATH.exists():
        return None
    for line in STAMP_PATH.read_text(encoding="utf-8").splitlines():
        if line.startswith("sha256:"):
            return line.split(":", 1)[1].strip()
    return None


def _write_stamp(sha256: str, *, file_count: int) -> None:
    STAMP_PATH.write_text(
        "\n".join(
            [
                "# Autogenerated by scripts/update_python_wheel_stamp.py",
                "# Hash of Python wheel sources (python/src + packaging metadata).",
                f"# inputs: {file_count} files",
                f"sha256: {sha256}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description="Update/verify the stamp that makes python-only changes visible to release automation."
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="Verify the stamp matches current python wheel inputs.",
    )
    args = ap.parse_args(argv)

    sha, n = _hash_inputs()
    current = _read_stamp_sha256()

    if args.check:
        if current == sha:
            return 0
        sys.stderr.write("python wheel stamp is out of date.\n")
        sys.stderr.write(f"expected sha256: {sha}\n")
        sys.stderr.write(f"current  sha256: {current or '<missing>'}\n")
        sys.stderr.write("\nFix:\n")
        sys.stderr.write("  python scripts/update_python_wheel_stamp.py\n")
        return 1

    _write_stamp(sha, file_count=n)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
